baseURL = 'https://blog.tiltowait.dev/'
languageCode = 'en-us'
title = 'do as sudo'
theme = 'bear'

[permalinks]
  blog = "/:slug"
  tags = "/blog/:slug"

[params]
  title = 'do as sudo'
  description = 'thoughts, dev notes, and musings about tech'
  favicon = 'images/favicon.png'

  hideMadeWithLine = true
  enablePostNavigator = true

[[menu.main]]
  name = 'home'
  url = '/'
  weight = 1

